#!/bin/bash
set -e

path_to_monitoring_checks_logs="/var/log/LEDMonitoring"

#base setup
nagios_dir="/usr/lib/nagios"
if [ ! -d $nagios_dir ]; then
#create the nagios folder
mkdir -p $nagios_dir/plugins
fi
#create LEDMonitoring folder in data/opt
mkdir -p /data/opt/LEDMonitoring
#copy files to dedicated directories
cp -R /usr/local/share/nagios_check/* $nagios_dir/plugins/
cp -R /usr/local/share/LEDMonitoring /data/opt/
# Example: create a log folder
echo "creating log folder LEDMonitoring"
mkdir -p $path_to_monitoring_checks_logs
echo "changing permissions on LEDMonitoring"
chmod 775 $path_to_monitoring_checks_logs
echo "creating log files for the monitoring"
touch $path_to_monitoring_checks_logs/debug_dvi.log
touch $path_to_monitoring_checks_logs/debug_cabinet.log
touch $path_to_monitoring_checks_logs/debug_brightness.log
touch $path_to_monitoring_checks_logs/debug_modules.log
touch $path_to_monitoring_checks_logs/debug_receiving_cards.log
touch $path_to_monitoring_checks_logs/debug_receiving_cards_temperature.log
touch $path_to_monitoring_checks_logs/debug_receiving_cards_voltage.log
touch $path_to_monitoring_checks_logs/debug_sender_cards.log
echo "changing permissions on LEDMonitoring"
chmod 775 $path_to_monitoring_checks_logs/debug_*
echo "setting owner of LEDMonitoring log folder"
chown root:root $path_to_monitoring_checks_logs
echo "updating permissions for LEDMonitoring folder"
chmod a+rwx /data/opt/LEDMonitoring
chmod a+rwx /data/opt/LEDMonitoring/*
chmod +x /$nagios_dir/plugins/*
echo "changing permission on ttyUSB"
sudo chmod +x /dev/ttyUSB*
echo installing pyserial
apt install python3-serial
echo "Done"

#testing nagios scripts