name: Build and Release Debian Package

on:
  # Trigger this workflow when you push a tag that starts with 'v', e.g. 'v1.0.0'
  push:
    tags:
      - "v*"

jobs:
  build-deb:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up dpkg-deb
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev
          sudo dpkg --clear-avail

      - name: Build Debian package
        id: build_deb
        run: |
          sudo dpkg --clear-avail
          # Create staging folder
          mkdir package

          # Copy all packaging content to staging
          chmod +x packaging/usr/local/bin/mytool
          cp -R packaging/* package/

          # Change permissions to executable
          chmod 755 /package/DEBIAN/postinst
          
          # Also copy the Python source into an appropriate location
          # so that it's packaged. We'll put it under /usr/local/share/mytool.
          mkdir -p package/usr/local/share/mytool
          cp -R src/main_tool.py package/usr/local/share/mytool/

          # Build .deb
          dpkg-deb --build package mytool_1.0.0_all.deb

      - name: Create or update GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}    # e.g. 'v1.0.0'
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Debian artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mytool_1.0.0_all.deb
          asset_name: mytool_1.0.0_all.deb
          asset_content_type: application/octet-stream
