name: Build and Release Debian Package

on:
  push:
    tags:
      - "v*"
    branches: [ "main" ]
jobs:
  build-deb:
    runs-on: self-hosted

    # Ensures that the default GITHUB_TOKEN can create/releases
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev
          sudo apt install python3-serial
      - name: Build Debian package
        id: build_deb
        run: |
          # Create staging folder
          mkdir package
          sudo dpkg --clear-avail
          # Copy all packaging content to staging
          chmod +x packaging/usr/local/bin/monitoring_tool
          cp -R packaging/* package/
          
          # Also copy the Python source into an appropriate location
          # so that it's packaged. We'll put it under /usr/local/share/monitoring_tool.
          if [ ! -d package/usr/local/share/monitoring_tool ]; then          
            mkdir -p package/usr/local/share/monitoring_tool/          
          fi
          # Change permissions to executable
          chmod 755 package/DEBIAN/postinst
          cp -R src/monitoring_listener.py package/usr/local/share/monitoring_tool/

          # Build .deb
          dpkg-deb --build package mytool_1.0.0.deb
      - name: Setup structure and files
        run: |
          ls package/
          nagios_dir="/usr/lib/nagios"
          if [ ! -d $nagios_dir ]; then
            #create the nagios folder
            sudo mkdir -p $nagios_dir/plugins
          fi
          sudo mkdir -p /data/opt/
          sudo cp package/usr/lib/share/nagios_checks/* $nagios_dir/plugins/
          sudo cp package/usr/lib/share/LEDMonitoring/ /data/opt/
      - name: Create or update GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # <-- Provided in env, not "with:"
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: true #todo replace to false when in 
      - name: Upload Debian artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # <-- Also required here
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mytool.deb
          asset_name: mytool.deb
          asset_content_type: application/octet-stream
